apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: pineapple
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: banana
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: banana-boat
  name: banana-boat
  namespace: pineapple
spec:
  containers:
  - image: nginx
    name: banana-boat
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
