apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cherry
spec: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: pit
  namespace: cherry
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: pit
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pit
  name: pit
  namespace: cherry
spec:
  containers:
  - image: nginx
    name: pit
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: stem
  namespace: cherry
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: stem
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stem
  name: stem
  namespace: cherry
spec:
  containers:
  - image: nginx
    name: stem
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
