apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: kiwi
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kiwi-secret-pod
  name: kiwi-secret-pod
  namespace: kiwi
spec:
  containers:
  - image: nginx
    name: kiwi-secret-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
