apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: coconut
spec: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: watermelon
  name: watermelon
  namespace: coconut
spec:
  containers:
  - image: nginx
    name: watermelon
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
