# setup nfs provisioner:
# https://blog.pistack.co.za/kubernetes-nfs-client-provisioner-on-arm/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /test
    server: 192.168.0.4
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: task-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-nfs
  labels:
    app: echo-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-nfs
  template:
    metadata:
      labels:
        app: echo-nfs
    spec:
      containers:
      - image: busybox
        name: echo-container
        volumeMounts:
          - mountPath: "/data"
            name: task-pv-storage
        command: ["ping", "127.0.0.1"]
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
