apiVersion: batch/v1
kind: Job
metadata:
  name: parallelism
  namespace: jobs
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
        - name: job
          image: busybox
          args:
            - /bin/sh
            - -c
            - echo "start"; sleep 10; echo "finish"
      restartPolicy: Never
